# be sure to add all "required" values...

# amazonec2, azure, digitalocean, harvester, vsphere, custom
# https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider
cloudprovider: vsphere # required

# cloud provider credentials (example: aws-creds)
cloudCredentialSecretName: vsphere-creds # required

# rancher manager url
rancher:
  cattle:
    url: # required (example: rancher.example.com)

### Configure information about the cluster you are creating here
cluster:
  name: "exampleCluster"
  config:
    kubernetesVersion: "v1.28.13+k3s1"
    globalConfig:
      cni: "canal" # Possible values: canal, calico, cilium, multus, none
    # If you want to disable the CNI, you can use the following configuration:
    # cni: "none"
    # flannelBackend: "none"

### Configure information about vCenter
vcenter:
  host: "vcenter.lab"

# For a complete list of config options, please look here:
# https://github.com/rancherfederal/rancher-cluster-templates/blob/customWork/charts/cluster-templates/templates/nodeconfig-vsphere.yaml
nodepools:
  - name: "control-plane"
    quantity: 1
    datacenter: "/Datacenter"
    datastore: "/Datacenter/datastore/vsanDatastore"
  # Specify one creationType: vm, template, library, legacy
    creationType: "library"
  # cloneFrom will need to match the corresponding creationType
  # For example, if you were cloning from a template, you would use:
  # creationType: "template"
  # cloneFrom: "/Datacenter/vm/Rocky9.4-minimal"
    cloneFrom: "Rocky9.4-minimal"
    contentLibrary: "MyContentLibrary"
    cloneFrom: "Rocky9.4-minimal"
    etcd: true
    controlplane: true
    worker: true
    cpuCount: 2
    diskSize: 20000
    memorySize: 4096
    cloudConfig: |
      #cloud-config
      echo "Put your cloud config here"
